#!/usr/bin/env bash
# This script displays the content of the current directory

for file in *; do
    if [ ! -h "$file" ] && [ -f "$file" ]; then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done
