#!/usr/bin/env bash
# Script to configure Nginx to run as nginx user and listen on port 8080

# Stop the Nginx service
service nginx stop

# Configure Nginx to run as the nginx user
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Update Nginx to listen on all active IPs on port 8080
sed -i '/listen 80 default_server;/ a listen 8080 default_server;' /etc/nginx/sites-available/default

# Start the Nginx service
service nginx start
