#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
sudo useradd -r -s /bin/false nginx || true
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80;/listen \[::\]:8080;/' /etc/nginx/sites-available/default
sudo systemctl restart nginx
